env:
  browser: true
  es2021: true
  node: true
plugins:
  - jest
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended' 
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
